### ISSUE TITLE
Update PyPi package

### ISSUE THREAD

**Issue by danielsilva** [mobolic/facebook-sdk#157]
Hello there,

First, want to thank you for sharing facebook-sdk for python.

Could you please update the PyPi package with the latest version? The current version available is facebook-sdk-0.4.0, uploaded on 2012-10-15! I've installed this package and had some weird incompatibilities and it took a long time till I find that I was using a pretty old version.

Like other devs, I found this issue (https://github.com/pythonforfacebook/facebook-sdk/issues/148) that pointed me to the misleading version problem.

Thank you again.

Best.

**Comment by homm** [comment]
> See the 1.0 milestone for issues that need to be resolved before 1.0.0 is released.

But we ask not about 1.0, we asking about some more resent version than released 2.5 years ago. On [April 30 with api version 1.0 deprecation](https://developers.facebook.com/docs/apps/changelog) the version in PyPI will became completely faulty.

Building the new shiny version for ever is not the best way for software development. There absolutely no reasons for delaying completed features until other are ready.
