### ISSUE TITLE
debug_access_token does not work if self.access_token is set

### ISSUE THREAD

**Issue by sagarchalise** [mobolic/facebook-sdk#276]
While debugging token, if we need to verify a token against an app, the implementation seems to give error.

This is due to override of 'access_token' in arguments in request method.

See:

https://github.com/pythonforfacebook/facebook-sdk/blob/master/facebook/__init__.py#L236

**Comment by martey** [comment]
Could you post some example code to clarify what the exact issue is?

**Comment by sagarchalise** [comment]
Sorry my bad, I guess I understand how this should be used in `debug_access_token`. Simple misunderstanding.

**Comment by sagarchalise** [comment]
Although I closed this issue , I still feel the folowing workflow should be valid but currently its not.

```
fb = GraphAPI(access_token='some_token')
fb.debug_access_token('app_id', 'app_secret')
```

**Comment by martey** [comment]
`debug_access_token` requires a token as its first parameter. Try:

````
fb = GraphAPI(access_token='some_token')
fb.debug_access_token(fb.access_token, 'app_id', 'app_secret')

````

You could also do:

````
fb = GraphAPI()
fb.debug_access_token('some_token', 'app_id', 'app_secret')
````

**Comment by sagarchalise** [comment]
@martey Your  first example won't work and that is what prompted me for issue post. Actually, the `access_token` initialized is not the parameter for debugging. So, I think if `access_token` is already set  the method `debug_access_token` should have some additional functionality. Currently, I am overriding the method and doing this:

`
debug_access_token(self, app_id, app_secret, token=None):
    if self.access_token:



`

**Comment by acpmasquerade** [comment]
`debug_access_token` should not account initialized `access_token`. 
Also, as per the nature of the method, it should be static type, which makes things more clear.

**Comment by kz26** [comment]
Sorry, I was the one who originally contributed this code! You're right, it's better off as a static method. I think the confusion originally came from the fact that for this method, `access_token` refers not to the token you're trying to debug, but the app access token. I'll fix this and submit a PR.

**Comment by kz26** [comment]
Fixed in #269. My approach is to check for an access_token in `args` or `post_args` and not override with self.token if that is the case.

**Comment by martey** [comment]
For future reference, please feel free to contact me before working on issues assigned to me (which means that I am either actively working on it, or I have concrete plans to do so in the near future).

**Comment by kz26** [comment]
Oops, didn't realize that. I'll keep that in mind for next time.
