### ISSUE TITLE
issue posting image to page as page owner

### ISSUE THREAD

**Issue by bbelderbos** [mobolic/facebook-sdk#301]
I suspect an issue in request()

        if self.access_token:
            # If post_args exists, we assume that args either does not exists
            # or it does not need `access_token`.
            if post_args and "access_token" not in post_args:
                post_args["access_token"] = self.access_token
            elif "access_token" not in args:
              args["access_token"] = self.access_token

       try:
            response = requests.request(method or "GET",
                                        FACEBOOK_GRAPH_URL + path,
                                        timeout=self.timeout,
                                        params=args,
                                        data=post_args,
                                        proxies=self.proxies,
                                        files=files)

I think args and post_args got confused. when I pass access_token as kwargs to request (via put_photo) it gets assigned to data via post_args, I think it needs to get into params via args, but it never gets into args

the problem is that when you want to post to a page as the page owner you need to use a page token (retrieved via me/accounts), not the regular user token

I only got it working directly setting the access_token attr on the graph instance, I don't think that is ideal though: 

        graph.access_token = page_token                                                                                 
        res = graph.put_photo(image=open(img, 'rb'), album_path="%s/photos" % id_, message=msg)

=> only after this it did post as page owner, e.g.
https://www.facebook.com/awesomereadingbob/

thanks
Bob

**Comment by kz26** [comment]
The way I usually do this is to simply create another GraphAPI() instance using the page access token.

**Comment by martey** [comment]
@kz26 is correct - I think the simplest solution is to create another GraphAPI instance. The SDK assumes that each GraphAPI object will be associated with a single access token.

> when I pass access_token as kwargs to request (via put_photo) it gets assigned to data via post_args, I think it needs to get into params via args, but it never gets into args

I don't think there is an easy way for `put_photo` to determine how kwargs need to be split between args and post_args. You could call the request method directly, though.

I am closing this issue, but if you want to submit documentation improvements as a pull request, they would be appreciated.
