### ISSUE TITLE
The request() function just use the old version of Graph API

### ISSUE THREAD

**Issue by bosihu** [mobolic/facebook-sdk#302]
I suspect an issue in request()
```
 response = requests.request(method or "GET",
                                        FACEBOOK_GRAPH_URL + path,
                                        timeout=self.timeout,
                                        params=args,
                                        data=post_args,
                                        proxies=self.proxies,
                                        files=files)
```
I think this function should use the version field, which one is defined as the parameter self.version. Otherwise, this function will use the old version number to request data from facebook server. So I advise modify it like this:
`response = requests.request(method or "GET",
                                        FACEBOOK_GRAPH_URL + self.version + "/" + path,
                                        timeout=self.timeout,
                                        params=args,
                                        data=post_args,
                                        proxies=self.proxies,
                                        files=files)`

**Comment by kz26** [comment]
If you look at the other functions in the codebase (put_wall_post, get_object, etc.) they already include the version prefix. I think it's best to leave the raw request method as-is since it allows you the freedom to specify the version on a per-request basis if for some reason you're dealing with more than one version of Graph API.

**Comment by bosihu** [comment]
I see. Good.

2016-07-29 4:02 GMT+08:00 kz26 <notifications@github.com>:

**Comment by martey** [comment]
Closing because I believe @kz26 is correct.
