### ISSUE TITLE
Logout no longer working in Flask example

### ISSUE THREAD

**Issue by jndoy** [mobolic/facebook-sdk#307]
Since the update of FB sdk 2.7, /logout no longer logs out. There is a console error message "Uncaught TypeError: Cannot read property 'accessToken' of null all.js:88"

**Comment by martey** [comment]
Can you let us know if changing `js.src` in base.html from `//connect.facebook.net/en_US/all.js` to `//connect.facebook.net/en_US/sdk.js` helps?

http://stackoverflow.com/q/38462764/113527 suggests that all of our examples and documentation should be using `sdk.js`, but it would be useful to know if additional changes are needed.

**Comment by jndoy** [comment]
Thanks. I did try both and the same problem was happening. It won't completely logout and it won't redirect to the login screen. Manually clearing the cookie seems to fix it temporarily and then it happens again. I checked all the code

**Comment by martey** [comment]
Looking at [the `index.html` template](https://github.com/mobolic/facebook-sdk/blob/dffacd6723619374e463d8acfae2c3f0fea71d01/examples/flask/app/templates/index.html) in the Flask example, I think it is possible that this is a bug in `//connect.facebook.net/en_US/all.js`.

@jndoy, can you confirm that this is still happening?

**Comment by jndoy** [comment]
I'm now using https://connect.facebook.net/en_US/sdk.js and it is working fine. Thank you
