### ISSUE TITLE
How to access status message 

### ISSUE THREAD

**Issue by abhi-84** [mobolic/facebook-sdk#309]
Hi
I need to access my last status message of my wall. How to use get_object to access status ?
Ex: to post on wall:   
def main():
  # Fill in the values noted in previous steps here
  cfg = {
    "page_id"      : "VALUE"
    "access_token" : "VALUE" 
    }

  api = get_api(cfg)
  msg = "Hello, world!"
  status = api.put_wall_post(msg)

def get_api(cfg):
  graph = facebook.GraphAPI(cfg['access_token'])
  # Get page token to post as the page. You can skip 
  # the following if you want to post as yourself. 
  resp = graph.get_object('me/accounts')
  page_access_token = None
  for page in resp['data']:
    if page['id'] == cfg['page_id']:
      page_access_token = page['access_token']
  graph = facebook.GraphAPI(page_access_token)
  return graph

Similarly, How can I read from wall ?
Please help

**Comment by abhi-84** [comment]
It doe not accept my facebook profile name as given in example. 
gives error: facebook.GraphAPIError: (#803) Some of the aliases you requested do not exist: Abhishek Kumar Srivastava
What could the way out?

**Comment by martey** [comment]
This issue tracker is for bug reports and feature requests. For general questions about how to use the library, please post to the [Google Group](https://groups.google.com/group/pythonforfacebook).
