### ISSUE TITLE
Facebook API rate limit handling

### ISSUE THREAD

**Issue by jvquarck** [mobolic/facebook-sdk#314]
As stated in Facebook documentation [rate limiting](https://developers.facebook.com/docs/graph-api/advanced/rate-limiting/) entry, Facebook will return a X-App-Usage header if the API usage is too high due to get requests, time of these requests or cputime consumed by these requests.

Is there any way to handle rate limit with the SDK? Or a way to get these values from the SDK?

**Comment by martey** [comment]
There are no specific functions for rate limiting in the SDK at this time.

Please note this issue tracker is primarily for bug reports. For further discussion of this issue or for other general questions about how to use the library, please post to the [Google Group](https://groups.google.com/group/pythonforfacebook).

**Comment by jvquarck** [comment]
My apologies, thanks for the heads up.

**Comment by rgupta2** [comment]
@martey 
Any update on this?

**Comment by martey** [comment]
> For further discussion of this issue or for other general questions about how to use the library, please post to the [Google Group](https://groups.google.com/group/pythonforfacebook).
