### ISSUE TITLE
I am getting this issue while creating post request

### ISSUE THREAD

**Issue by clock21am** [mobolic/facebook-sdk#315]
Traceback (most recent call last):
  File "facebooktoken.py", line 6, in <module>
    post = graph.get_object(id='education-experience-id')
  File "/usr/local/lib/python2.7/dist-packages/facebook/__init__.py", line 105, in get_object
    return self.request(self.version + "/" + id, args)
  File "/usr/local/lib/python2.7/dist-packages/facebook/__init__.py", line 272, in request
    raise GraphAPIError(result)
facebook.GraphAPIError: (#803) Some of the aliases you requested do not exist: education-experience-id

**Comment by martey** [comment]
You're receiving an error because https://www.facebook.com/education-experience-id does not exist.

Is it possible that `education-experience-id` is supposed to be the name of a variable instead of a string?

**Comment by clock21am** [comment]
but i got the issue with post-id also

**Comment by clock21am** [comment]
see this is the code 

graph = facebook.GraphAPI(access_token=tokeen,version='2.2')
post = graph.get_object(id='post_id')
print(post['message'])

**Comment by clock21am** [comment]
this is also
{
  "error": {
    "message": "(#803) Some of the aliases you requested do not exist: {event-id}",
    "type": "OAuthException",
    "code": 803,
    "fbtrace_id": "BPL4riD69/q"
  }
}

**Comment by martey** [comment]
The `id` parameter in `get_object` is the name or ID number of the object that you are trying to retrieve.

If you try:
```python
my_profile = graph.get_object(id="me")
```
You won't get an error because "me" redirects to your actual Facebook profile.

`post_id`, `event_id`, and the other strings in the documentation examples are supposed to be replaced with actual post and event IDs.

**Comment by clock21am** [comment]
the above is not working even

**Comment by clock21am** [comment]
Thanks alot it started working :+1:

**Comment by martey** [comment]
If you have further issues or questions, please feel free to post a message to the [Google Group](https://groups.google.com/group/pythonforfacebook).
