### ISSUE TITLE
total_count of likes

### ISSUE THREAD

**Issue by jsuit** [mobolic/facebook-sdk#316]
Is there a way to get the total_count of likes for a post, as in here: https://developers.facebook.com/docs/graph-api/reference/v2.8/object/likes

**Comment by martey** [comment]
Please use the [Google Group](https://groups.google.com/forum/#!forum/pythonforfacebook) to ask questions. This issue tracker is for bug reports only.

**Comment by batuhanates0** [comment]
(#12) singular statuses API is deprecated for versions v2.4 and higher


my like code ;
`		 $data = array(
    'id' => '1730223957216833'
  );
  $result = $facebook->api('likes')
                     ->post($data, 'json');
  echo $result;
} catch(Exception $e) {
  echo $e->getMessage();
}
`
