### ISSUE TITLE
Add API version 2.8 to the valid list

### ISSUE THREAD

**Issue by jaddison** [mobolic/facebook-sdk#324]

**Comment by guillermo-carrasco** [comment]
HI there, when will this change be available via `pip`? :-) Thanks!

**Comment by martey** [comment]
See https://facebook-sdk.readthedocs.io/en/v2.0.0/install.html#installing-from-git.

**Comment by guillermo-carrasco** [comment]
yup I know, thanks. Sorry I asked the wrong question. The question was more of: when do you plan to build a new release for **PyPi**? :-D Thanks!

**Comment by martey** [comment]
New releases occur when currently outstanding issues (see https://github.com/mobolic/facebook-sdk/milestone/3) are resolved.
