### ISSUE TITLE
Please provide instructions on how to run the flask example

### ISSUE THREAD

**Issue by lohriialo** [mobolic/facebook-sdk#331]
Please provide instructions on how to run the flask example

**Comment by martey** [comment]
This issue tracker is for bug reports and feature requests. For questions about how to use the Flask example, please post to the [Google Group](https://groups.google.com/group/pythonforfacebook). If you decide to post there, you might want to follow the advice in http://zellwk.com/blog/asking-questions/ to increase the chances that your question is answered.
