### ISSUE TITLE
Live video Reaction

### ISSUE THREAD

**Issue by diegodeodati** [mobolic/facebook-sdk#332]
Hi i would to know if is possible have example code to retrieve information about live reaction on video live.

Thanks

**Comment by martey** [comment]
This issue tracker is for bug reports and feature requests. For general questions about how to use the library, please post to the [Google Group](https://groups.google.com/group/pythonforfacebook). If you decide to post there, you might want to follow the advice in http://zellwk.com/blog/asking-questions/ to increase the chances that your question is answered.
