### ISSUE TITLE
Retrieving headers from request

### ISSUE THREAD

**Issue by alexk307** [mobolic/facebook-sdk#333]
Hello, I am trying to get the headers sent back from Facebook on their response in the `get_object` method, but the response only returns JSON. Is there a way to return the entire response, including the headers?

**Comment by martey** [comment]
This issue tracker is for bug reports and feature requests. For general questions about how to use the library, please post to the [Google Group](https://groups.google.com/group/pythonforfacebook). If you decide to post there, you might want to follow the advice in http://zellwk.com/blog/asking-questions/ to increase the chances that your question is answered.
