### ISSUE TITLE
get_user_from_cookies reading wrong data

### ISSUE THREAD

**Issue by kwatog** [mobolic/facebook-sdk#335]
I'm developing my app on dev.mydomain.com while my live site is on mydomain.com

While testing, request.COOKIES is actually returning the data from mydomain.com instead from dev.mydomain.com

after deleting the cookies on the live site, the dev site worked. both sites are on the same server. 

arguably, this is not a problem on facebook-sdk.

**Comment by martey** [comment]
This issue tracker is only for bug reports and feature requests directly involving facebook-sdk. For general questions about how to use the library, please post to the [Google Group](https://groups.google.com/group/pythonforfacebook). If you decide to post there, you might want to follow the advice in http://zellwk.com/blog/asking-questions/ to increase the chances that your question is answered.
