### ISSUE TITLE
Sharing posts

### ISSUE THREAD

**Issue by Fireobridy** [mobolic/facebook-sdk#336]
Would be great to have possibility to share posts.

**Comment by martey** [comment]
Can you provide more details about what exactly you are looking for?

**Comment by martey** [comment]
@Fireobridy, since you haven't responded, I am going to close this issue. Feel free to comment here if you want to - I will be notified when you do.

**Comment by kodeine** [comment]
For example theres a post on news feed, how can we share it on my wall via api

**Comment by martey** [comment]
The invitation to comment was specifically for @Fireobridy, since I needed more information to determine whether this was a bug, feature request, or something else.

As always, general questions about using the Graph API should be posted to the Google Group.
