### ISSUE TITLE
Python Facebook graph API post URL with preview

### ISSUE THREAD

**Issue by pratibhajagnere** [mobolic/facebook-sdk#346]
When I post any URL using put_wall_post, it is posting it as text and not with preview. Here is the related question http://stackoverflow.com/questions/42358277/python-facebook-graph-api-post-url-with-preview.

Can you please tell me how can I get URL posted with preview?

**Comment by martey** [comment]
Please post questions like this to the Google Group at https://groups.google.com/forum/#!forum/pythonforfacebook instead of creating issues here.
