### ISSUE TITLE
Using new version of facebook Graph API

### ISSUE THREAD

**Issue by gracechristina** [mobolic/facebook-sdk#348]
Hi, I used the function graph = facebook.GraphAPI(access_token) and it gives me a lot of data such as link,message,shares,likes and so on. 
However, when I use graph = facebook.GraphAPI(access_token,version="2.6"), it doesn't give me as much data as I need. It only gives me created_time,message,id and story. Why is that so? Is there any way to solve it? Thank you

**Comment by martey** [comment]
Please post questions like this to the Google Group at https://groups.google.com/forum/#!forum/pythonforfacebook instead of creating issues here.
