### ISSUE TITLE
hi i want to make post in fb using facebook-sdk and it return error like ""

### ISSUE THREAD

**Issue by kartikdanidhariya** [mobolic/facebook-sdk#349]
hi i want to make post in fb using facebook-sdk and it return error like " An active access token must be used to query information about the current user." 

my code is 

`import urllib
import facebook

FACEBOOK_APP_ID = 'XXXXXXXXXXXX'
FACEBOOK_APP_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
FACEBOOK_PROFILE_ID = 'XXXXXXXXXXXXXXXXXXXXXXXXXX'
oauth_args = dict(
  client_id = FACEBOOK_APP_ID,
  client_secret = FACEBOOK_APP_SECRET,
  grant_type = 'client_credentials')
oauth_response = urllib.urlopen('https://graph.facebook.com/oauth/access_token?'
  + urllib.urlencode(oauth_args)).read()

print "oauth_response",oauth_response
print "oauth_response.split('=')[1]",oauth_response.split('=')[1]
  

attach = {
  "name": 'Hello',
  "link": 'http://www.link.com',
  "caption": 'test',
  "description": 'some test',
  "picture" : 'http://img/picture.png',
}

facebook_graph = facebook.GraphAPI(oauth_response.split('=')[1])
print "facebook_graph",facebook_graph
try:
    response = facebook_graph.put_wall_post('', attachment=attach)
except facebook.GraphAPIError as e:
    print "erorr",e`

so it return error like  An active access token must be used to query information about the current user.
i check that i get auth token but when  try to post something at that time it raise the error

**Comment by martey** [comment]
This issue tracker is for bug reports and enhancement requests only. Please send questions about the library or using the Graph API in general to the [repository's Google Group](https://groups.google.com/forum/#!forum/pythonforfacebook).
