### ISSUE TITLE
ImportError: No module named 'facebook'

### ISSUE THREAD

**Issue by snydez** [mobolic/facebook-sdk#350]
Hi 
i'm new on Python and i'm trying to run of the code inside test folder (of the sdk), it is error : `ImportError: No module named 'facebook'`

any advise?
thanks

**Comment by martey** [comment]
Hi,

Please post your question to the [Google Group](https://groups.google.com/forum/#!forum/pythonforfacebook). It would be helpful if you include as many details as possible, including the exact commands you inputted to get to your error, your ultimate purpose, and what version of the SDK you are using.
