### ISSUE TITLE
Facebook Token Refresh without user action 

### ISSUE THREAD

**Issue by Chuck-Aguilar** [mobolic/facebook-sdk#355]
My "Issue" is more a question than an issue. 

The Access Token has a duration of 60 days. And after 60 days there should be a little "re-logging" or something like that and so can the Token be refreshed. 

Now my questions. 

Can we do that, without the user action? I mean, if we make a request (e.g. /me/), will the token refreshed? 

And just in case, if the user died, can we update the token every 55 days or so, with some request? 

I'm using the Facebook-SDK for some App that works with death people. (I know, a bit creepy, but someone had to do it :) ) and that's why the question came. 

Maybe someone tried something like that.

**Comment by martey** [comment]
Since this is both a question and deals with the Graph API instead of facebook-sdk in particular, it would be better to post to [the Google Group](https://groups.google.com/group/pythonforfacebook), as described in the README and other documentation.
