### ISSUE TITLE
How to get the public location and hometown based on profile id?

### ISSUE THREAD

**Issue by philipperemy** [mobolic/facebook-sdk#356]
The location and hometown are public when I browse on the profile via facebook.com

But when I try to get some information with this command:

```
graph.get_object(profile_id)
```

I have only those fields:
```
<class 'list'>: ['last_name', 'updated_time', 'id', 'first_name', 'link', 'middle_name', 'name']
```

Any ideas guys?

Thanks in advance!

**Comment by martey** [comment]
Please post your question to [the project's Google Group](https://groups.google.com/group/pythonforfacebook) - this issue tracker is only for bug reports and enhancement requests.
