### ISSUE TITLE
pip install version not installing latest

### ISSUE THREAD

**Issue by jwwtaker** [mobolic/facebook-sdk#363]
attempting to install version 2.0.0 to get the latest Facebook SDK versions but even when i do sudo pip install facebook-sdk --upgrade or if i do sudo pip install facebook-sdk==2.0.0 it ALWAYS installs 1.0.0

**Comment by jwwtaker** [comment]
the logs during install say this

Downloading/unpacking facebook-sdk==2.0.0
  Running setup.py egg_info for package facebook-sdk
    
    warning: no files found matching '*.ico' under directory 'examples'
    warning: no files found matching '*.yaml' under directory 'examples'
  Requested facebook-sdk==2.0.0, but installing version 1.0.0

**Comment by martey** [comment]
I can't replicate this based on the information that you have given:

```shell
martey@durandal:~$ mkvirtualenv issue-363
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/martey/.virtualenvs/issue-363/bin/python2
Also creating executable in /home/martey/.virtualenvs/issue-363/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
(issue-363) martey@durandal:~$ pip install facebook-sdk==2.0.0
Collecting facebook-sdk==2.0.0
  Using cached facebook_sdk-2.0.0-py2-none-any.whl
Collecting requests (from facebook-sdk==2.0.0)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Installing collected packages: requests, facebook-sdk
Successfully installed facebook-sdk-2.0.0 requests-2.13.0
```
It would help if you could provide the version of Python you are using, your operating system, as well as whether you have any other Python package repository (e.g. not just pypi.python.org) configured.

**Comment by jwwtaker** [comment]
I am running Python 2.7.10, i have not changed the repository and it doesn't seem to make sense.  It looks as if the correct package is downloaded but the installer installs 1.0?  here is the dump of my install and show commands.
`pip install facebook-sdk --upgrade
Downloading/unpacking facebook-sdk from https://pypi.python.org/packages/eb/a4/b5173c2465ec81421d2fc055d822d87dd5fb3cfaaa2ceac2f96bcfb52d5f/facebook-sdk-2.0.0.tar.gz#md5=07a60daf055cc792ed842234432f1ecb
  Running setup.py egg_info for package facebook-sdk
    
    warning: no files found matching '*.ico' under directory 'examples'
    warning: no files found matching '*.yaml' under directory 'examples'
Downloading/unpacking requests from https://pypi.python.org/packages/16/09/37b69de7c924d318e51ece1c4ceb679bf93be9d05973bb30c35babd596e2/requests-2.13.0.tar.gz#md5=921ec6b48f2ddafc8bb6160957baf444 (from facebook-sdk)
  Running setup.py egg_info for package requests
    
Installing collected packages: facebook-sdk, requests
  Found existing installation: facebook-sdk 1.0.0
    Uninstalling facebook-sdk:
      Successfully uninstalled facebook-sdk
  Running setup.py install for facebook-sdk
    
    warning: no files found matching '*.ico' under directory 'examples'
    warning: no files found matching '*.yaml' under directory 'examples'
  Found existing installation: requests 2.9.1
    Uninstalling requests:
      Successfully uninstalled requests
  Running setup.py install for requests
    
Successfully installed facebook-sdk requests
Cleaning up...
(mitu)Andrews-Retina-15-MBP:mitu root# pip show facebook-sdk
---
Name: facebook-sdk
Version: 1.0.0
Location: /Users/aamir/Sites/mitu/mitu/mitu/lib/python2.7/site-packages
Requires: requests
`

**Comment by martey** [comment]
What version of pip do you have installed?

**Comment by ptraverse** [comment]
I've been having this problem too. burned a whole day on it and finally got it by hacking my virutalenv's copy of `facebook/__init__.py` to `default_version = VALID_API_VERSIONS[-1]` , i.e. use the LAST index of VALID_API_VERSIONS rather than the first... it smells bad but works

![screen shot 2017-04-26 at 3 28 16 pm](https://cloud.githubusercontent.com/assets/2491817/25459847/2c535a00-2a95-11e7-89c9-f20b9c96dc08.png)

**Comment by martey** [comment]
I don't think that this is a bug in facebook-sdk. I think it could be a bug in pip that has been fixed, so I would appreciate it if someone experiencing this bug could post the version of pip that they are using.

**Comment by ptraverse** [comment]
```
pip --version
pip 9.0.1 from /root/FBPY-SDK/NEW/local/lib/python2.7/site-packages (python 2.7)
```

**Comment by ptraverse** [comment]
```
(NEW) root FBPY-SDK # pip freeze
appdirs==1.4.3
bottle==0.12.13
chardet==3.0.2
Cheetah==2.4.4
colorama==0.2.5
configobj==4.7.2
contextlib2==0.5.4
demjson==2.2.4
facebook-sdk==2.0.0
facebookads==2.9.1
gunicorn==19.6.0
html5lib==0.999
jsonpatch==1.3
jsonpointer==1.0
Markdown==2.6.8
MySQL-python==1.2.3
oauth==1.0.1
packaging==16.8
pam==0.1.4
peewee==2.8.1
pipdeptree==0.9.0
prettytable==0.7.2
pyparsing==2.2.0
pyserial==2.6
PyYAML==3.10
raven==5.32.0
requests==2.2.1
six==1.6.0
ssh-import-id==3.21
urllib3==1.7.1
yolk==0.4.3
zope.interface==4.0.5
```

**Comment by jwwtaker** [comment]
You are probably right. I could not get the issue fixed, so i started a whole new virtualenv with the newest version of pip and it seems fine now. it installed the 2.0 version.

**Comment by martey** [comment]
@ptraverse, does creating a new virtualenv fix the issue for you as well?
