### ISSUE TITLE
Issue with Python 3.6

### ISSUE THREAD

**Issue by sidmah342t** [mobolic/facebook-sdk#366]
I am getting the below error after installling the facebook sdk and running the program
Traceback (most recent call last):
File “C:/Users/xxx/PycharmProjects/facebook-sdk/likefbpages.py”, line 11, in
graph = facebook.GraphAPI(usertoken)
File “C:\Users\xxx\PycharmProjects\facebook-sdk\facebook\__init__.py”, line 88, in init
self.session = session or requests.Session()
AttributeError: module ‘requests’ has no attribute ‘Session’﻿

**Comment by martey** [comment]
I think this is unlikely to be a bug in the SDK, so I am going to close this. Posting a message to the Google Group is the best way to get support for questions like this, and I've noticed that [you have already sent a message there](https://groups.google.com/d/msg/pythonforfacebook/h576l5Rb2OQ/Y9TviYCKAwAJ).
