### ISSUE TITLE
Flask example needs to provide Facebook SDK version

### ISSUE THREAD

**Issue by cheezecat** [mobolic/facebook-sdk#370]
### Version of the SDK being used
2.0.0

### Expected Behavior
Flask example should log into facebook.

### Actual Behavior
You get an error from Facebook about the version not being specified.
https://github.com/mobolic/facebook-sdk/blob/master/examples/flask/app/templates/base.html#L29

### Steps to Reproduce
Try to use flask example

**Comment by martey** [comment]
Is this the same issue as #365?

**Comment by cheezecat** [comment]
@martey It looks pretty similar.  Probably the same issue.

**Comment by martey** [comment]
Then I am going to close this issue. Additional comments should be posted on #365.
