### ISSUE TITLE
Support for Python 3.6

### ISSUE THREAD

**Issue by Rdbaker** [mobolic/facebook-sdk#372]
### Version of the SDK being used
```bash
$ pip freeze | grep face
facebook-sdk==2.0.0
```

### Expected Behavior
```python
>>> import facebook
>>> # the next line should not raise an error
>>> facebook.GraphAPI
>>> # yay!
```

### Actual behavior
```python
>>> import facebook
>>> # the next line should not raise an error
>>> facebook.GraphAPI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'facebook' has no attribute 'GraphAPI'
```

### Steps to Reproduce
This *only* happens in Python 3.6. Watch this:

```bash
$ workon my-35-virtualenv
(my-35-virtualenv) $ python --version
3.5.2
(my-35-virtualenv) $ python
>>> import facebook
>>> facebook.GraphAPI
>>> # yay!
>>> exit(0)
(my-35-virtualenv) $ workon my-36-virtualenv
(my-36-virtualenv) $ python --version
3.6.1
(my-36-virtualenv) $ python
>>> import facebook
>>> facebook.GraphAPI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'facebook' has no attribute 'GraphAPI'
```

This leads me to believe that python 3.6 changed how imports work. I'll do some research on 3.6 imports, but I wanted this issue to be known. From what I saw there aren't any issues here nor on the facebook developer forum that address this.

**Comment by martey** [comment]
I can't replicate this in Python 3.6.1.

Can you confirm that `facebook-sdk` is installed in your 3.6 virtualenv and not [`facebook`](https://pypi.python.org/pypi/Facebook)?

**Comment by Rdbaker** [comment]
Yes. It was `facebook-sdk` that I had installed and not the other library. After installing from the git repo instead of installing from pypi, I did not have this problem. Even though I installed a different version (`facebook-sdk-3.0.0a0` and `v2.0.0` from pypi), the problem vanished.

I'm going to close this issue because it seems to be fixed in v3.

**Comment by martey** [comment]
I am actually going to reopen this - our documentation does not say we support 3.6, and our automated test suite does not test on it, but we should.

The "different versions" are because [several changes have been made since the release of v2.0.0](https://github.com/mobolic/facebook-sdk/compare/v2.0.0...master), but since I tested on v2.0.0, I don't think that is the reason it is now fixed.

This seems extremely similar to #366. If anyone else is having this AttributeError issue, **please create a new bug** with the results of `python -v`.

**Comment by Rdbaker** [comment]
I just blew away my virtualenv and tried again from scratch.

```bash
$ mkvirtualenv py-36-test -p ~/.pyenv/versions/3.6.1/bin/python
...
(py-36-test) $ pip install facebook-sdk
Collecting facebook-sdk
  Downloading facebook-sdk-2.0.0.tar.gz
...
(py-36-test) $ python --version
Python 3.6.1
(py-36-test) $ python
>>> import facebook
>>> facebook.GraphAPI
<class 'facebook.GraphAPI'>
>>> # yay!
```

I'm not sure exactly what was wrong, but trying again with a clean virtualenv fixed this problem. Might be that it didn't play nicely with some configuration I messed with in my previous virtualenv, but it's working now.

Sorry for the spam about this -- it looks like a non-issue, but I'll let you decide if you want to close this or if you want me to try to figure out what was going on with my virtualenv (I still have the old one)
