### ISSUE TITLE
 want only some of my friends to see my post .is it possible to  post with privacy option using facebook sdk?

### ISSUE THREAD

**Issue by ChaitanyaYalamareddy** [mobolic/facebook-sdk#381]
privacy = {'value': 'CUSTOM','allow': '10085565322' }
pri = json.dumps(privacy, ensure_ascii=True)
graph.put_object(parent_object='me', connection_name='feed',message='Hello',privacy=pri)

I tried the above code  and got an exception 
facebook.GraphAPIError: (#100) Only friends may be specified in allow and deny lists

**Comment by martey** [comment]
> If you have a general question about how to use this SDK or Facebook's Graph API, you should be posting a question at https://groups.google.com/group/pythonforfacebook instead of creating an issue here.

**Comment by ChaitanyaYalamareddy** [comment]
I have already posted in google plus group before posting here .i have not got any suggestions and replies . So i posted here so that owner might reply . If you have some time .please have a look at the problem and suggest me
