### ISSUE TITLE
Version number should be in the following format: #.# (e.g. 2.0).

### ISSUE THREAD

**Issue by marvinschenkel-infoready** [mobolic/facebook-sdk#395]
### Version of the SDK being used
facebook-sdk-2.0.0

### Expected Behavior
Able to initiate a Graph object for version 2.10 of the API

### Actual Behavior
facebook.GraphAPIError:  Version number should be in the following format: #.# (e.g. 2.0).

### Steps to Reproduce
import facebook

graph = facebook.GraphAPI(access_token='xx', version='2.10')

Looks like the regexp to check the version number needs to be updated to support #.## instead of just #.#.

**Comment by marvinschenkel-infoready** [comment]
look s like it's fixed in 3.0 alpha

**Comment by asfaltboy** [comment]
Any chance 3.0 can get a release? Or perhaps we can cherry-pick/back-port the fix to an 2.X ver?

**Comment by martey** [comment]
See https://groups.google.com/d/msg/pythonforfacebook/a-7cLVLXncg/DSi8NmLRBAAJ.
