### ISSUE TITLE
GraphAPIError: (#100) param X must be an array

### ISSUE THREAD

**Issue by jplehmann** [mobolic/facebook-sdk#401]
### Version of the SDK being used
2.0 and FB Api 2.7

### Expected Behavior
When I try to post a photo with `put_object` with `tags` as well as when I try to post to `feed` with `attached_media` (to create a post with multiple photos) I expect great success.

### Actual Behavior

The error: 

> GraphAPIError: (100) param attached_media must be an array.

When I examine the `post_data` being used, it looks to correctly be trying to pass an array.

For example:
```
{'access_token': '...', 'caption': '...', 'attached_media': [{'media_fbid': u'1234'}, {'media_fbid': u'1234'}, {'media_fbid': u'1234'}, {'media_fbid': u'1234'}]}
```

### Steps to Reproduce

The photo/tags is easier to try. This works with the exception of the tags parameter, which gives similar error to the above.
```
api.put_object(parent_object='me', connection_name='photos', url=image_url, caption=caption, tags=[{'tag_uid':1234}])
```
The tags parameter is shown at: https://developers.facebook.com/docs/graph-api/reference/page/photos/

At first I thought maybe I was using a specific endpoint incorrectly, but then when I encountered it again I knew it was a more general problem with my usage or the SDK.

**Comment by pitzlabs** [comment]
tag_array = [{'tag_uid':1234},]
api.put_object(parent_object='me', connection_name='photos', url=image_url, caption=caption, tags=json.dumps(tag_array))

**Comment by martey** [comment]
Thanks for the example @pitzlabs!

Using JSON for Graph API "lists" is documented in https://developers.facebook.com/docs/graph-api/using-graph-api#parameters, but could be better exposed in our documentation.

I think it would make sense to have an example of uploading a photo with tags in the `put_photo` section of the [API reference](https://github.com/mobolic/facebook-sdk/blob/master/docs/api.rst), and would love to see a pull request to this effect. @jplehmann, could you let me know if you want to work on this?

**Comment by jplehmann** [comment]
@martey I wouldn't mind doing that but the thing I was using the sdk for is on hold anyway so I'm swamped with other stuff at the moment.  I appreciate all the feedback here!

**Comment by akhil-soomuch** [comment]
Found a simple solution. just convert the list to a string and try, it will work. You are welcome.
