### ISSUE TITLE
SDK does not return all places

### ISSUE THREAD

**Issue by williamfolkner** [mobolic/facebook-sdk#403]
### Version of the SDK being used

3.0.0a0 (pip list shows that)

### Expected Behavior

Such code:
fb_accesstoken = fb.GraphAPI().get_app_access_token(cg.app_id,cg.secret)

graph = fb.GraphAPI(fb_accesstoken, version="2.11")

coordinates = '55.760007,37.665491

places = graph.search(type='place',
                      center = coordinates,
                      distance = 500)

Should return the same result as pasting:

search?type=place&center=55.760007,37.665491&distance=500

into Graph API explorer:

https://developers.facebook.com/tools/explorer/?method=GET&path=search%3Ftype%3Dplace%26center%3D55.760007%2C37.665491%26distance%3D500&version=v2.11

### Actual Behavior

However, the result in Python ignores the first line of result:

    { "name": "Gazgolder club",
      "id": "431917656900531"
    },

### Steps to Reproduce

Are described above

**Comment by martey** [comment]
I can't replicate this error:

````python
import facebook
graph = facebook.GraphAPI("...access token from Graph API Explorer redacted...")
places = graph.search(type='place', center="55.760007,37.665491", distance=500)
places["data"][0]["name"], places["data"][0]["id"]

(u'Gazgolder club', u'431917656900531')
````

@williamfolkner, are you still experiencing this?

**Comment by martey** [comment]
Closing due to lack of reporter response and the fact that this feature (finding places through search) has been deprecated by Facebook: https://developers.facebook.com/blog/post/2018/04/04/facebook-api-platform-product-changes/
