### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by skorokithakis** [mobolic/facebook-sdk#410]
Hello,  
could you cut a release? The latest supported API version of v2 (2.7) is being deprecated, and my application will stop working because the library doesn't support anything after that.

**Comment by skorokithakis** [comment]
Ah, sorry, it seems that they're deprecating 2.5, and not 2.7. I guess we have a bit more time then.

**Comment by awaisdar001** [comment]
Please release to 2.12

**Comment by martey** [comment]
General questions like this should be posted to https://groups.google.com/group/pythonforfacebook. In this case, [your question has already been answered there](https://groups.google.com/forum/#!msg/pythonforfacebook/a-7cLVLXncg/DSi8NmLRBAAJ).
