### ISSUE TITLE
Add new versions to VALID_API_VERSIONS in released SDK version

### ISSUE THREAD

**Issue by eduardostalinho** [mobolic/facebook-sdk#413]
### Version of the SDK being used
2.0.0

### Expected Behavior
Support 2.9 Graph API version

### Actual Behavior
![2018-04-10-173421_1073x170_scrot](https://user-images.githubusercontent.com/418606/38582228-70f8f904-3ce5-11e8-8720-06af5eb6c32a.png)

### Steps to Reproduce
Calling `facebook.GraphAPI` with `version=2.9`

### Additional info:
Please, just update the version in PyPI, so i don't have to install the sdk from an unstable branch directly via git.

**Comment by martey** [comment]
> Please, just update the version in PyPI, so i don't have to install the sdk from an unstable branch directly via git.

If you don't want to install from a branch, pin your installation to a specific commit (e.g. `pip install -e git+https://github.com/mobolic/facebook-sdk.git@cbbe56f00ae7cb838f5dd5e1ca46671a6ec7b0a2#egg=facebook-sdk`).
