### ISSUE TITLE
Unsupported get request. Object with ID ...

### ISSUE THREAD

**Issue by Sandeepsr** [mobolic/facebook-sdk#414]
If you have a general question about how to use this SDK or Facebook's Graph API, you should be posting a question at https://groups.google.com/group/pythonforfacebook instead of creating an issue here. Bugs in the Graph API should be reported at https://developers.facebook.com/bugs/.

PLEASE DELETE THE ABOVE AFTER READING IT AND FILL IN EACH OF THE FOLLOWING SECTIONS.

### Version of the SDK being used
2.12
### Expected Behavior
Should get the event details from a public page.
Access token are fine/not expired

### Actual Behavior
Getting a exception since 3rd April:
Unsupported get request. Object with ID 'xxxxxx does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

### Steps to Reproduce
def get_events(user):
    events = list()
    graph = facebook.GraphAPI(ACCESS_TOKEN)
    profile = graph.get_object(user)
    posts = graph.get_connections(profile['id'],'events',fields='id,attending_count,cover,description,end_time,start_time,name,place,updated_time',since=sincet)

**Comment by martey** [comment]
There is no version 2.12 of this SDK. The error message you are receiving suggests that your issue is with the Graph API. You should either post this with more information at the Google Group or report it as a bug on Facebook's bug tracker.
