### ISSUE TITLE
Insecure M5 hash function in Instagram API code

### ISSUE THREAD

**Issue by STANAPI** [mobolic/facebook-sdk#419]
Hello, fellow developers! There seems to be two insecure parts in the Instagram API codes, as it's using MD5 hash function.

The two parts look like this below:
----------------------------------------------------------------
    def __init__(self, username, password, debug=False, IGDataPath=None):
        m = hashlib.md5()
        m.update(username.encode('utf-8') + password.encode('utf-8'))
----------------------------------------------------------------
    def generateDeviceId(self, seed):
        volatile_seed = "12345"
        m = hashlib.md5()
        m.update(seed.encode('utf-8') + volatile_seed.encode('utf-8'))
        return 'android-' + m.hexdigest()[:16]

What are the potential risk of this? Is there anyway to improve?

![image](https://user-images.githubusercontent.com/39898500/40902303-2654560e-6806-11e8-83d5-6ad09c875e48.png)

**Comment by martey** [comment]
The code snippets you mentioned do not exist in this library. I think you want to file this bug somewhere else.
