### ISSUE TITLE
Support for Facebook Graph API v3.1

### ISSUE THREAD

**Issue by maxhallhatesm3** [mobolic/facebook-sdk#429]
-> SDK v3.0.0, Facebook Graph API v3.1

-> It not to work, because there is not support.

-> It did not work; "Valid API versions are '2.7', '2.8', '2.9', '2.10', '2.11', '2.12', '3.0''

-> Generate FB SDK 3.1 key
-> Attempt to use that key with facebook-sdk v3.0.0

**Comment by thomakl** [comment]
Hi,

Everytime I run my script I get : 

`> facebook.GraphAPIError: Error validating application. Application has been deleted.`

Is this related ?

By the way how is the sdk going to by-pass the App Review from Facebook ? Do we need to create a Facebook App to make it work ?

Thank you for your time,

**Comment by martey** [comment]
@thomakl, please use [the Google Group](https://groups.google.com/forum/#!forum/pythonforfacebook) for support questions.

**Comment by dacoconuttman** [comment]
Would adding support for v3.1 just consist of adding "3.1" to VALID_API_VERSIONS and run existing tests to make sure it works? None of the changes between 3.0 and 3.1 seem to affect facebook-sdk. I tried running the unit tests with version 3.1 and it passed them all except test_parse_signed_request_when_correct, but that's probably because I'm testing with a different app secret than the cookies were signed with.

**Comment by martey** [comment]
> Would adding support for v3.1 just consist of adding "3.1" to VALID_API_VERSIONS and run existing tests to make sure it works?

You would also need to update the CHANGELOG. See https://github.com/mobolic/facebook-sdk/pull/418 for an example.

**Comment by reagle** [comment]
I'm new to the FB API and this package and have been trying to get a trivial example to work. I am unable to do so. I don't know if this has to do with API versions or if your documentation is out of date?

**Comment by martey** [comment]
This issue tracker is for bug reports and feature requests. For general questions about how to use the library, please post to the [Google Group](https://groups.google.com/group/pythonforfacebook). If you decide to post there, you might want to follow the advice in http://zellwk.com/blog/asking-questions/ to increase the chances that your question is answered.
