### ISSUE TITLE
put_object doesn't attach several photos

### ISSUE THREAD

**Issue by thelotusflower** [mobolic/facebook-sdk#433]

**Comment by martey** [comment]
Thanks for reporting this, and using the issue template, but this isn't currently actionable without more information.

You state that the method "used to" work. Was this with an older version of the SDK? If so, which one? Which version of the Graph API are you using?

> Use put_object method with parameter like {'link': '[link to FB photo]'}

Please provide actual code.

**Comment by martey** [comment]
> My suspision is it's some kind of problem with facebook API

As the issue template states, this tracker is only for bugs with facebook-sdk. Graph API bugs should be reported to Facebook at https://developers.facebook.com/support/bugs/.
