### ISSUE TITLE
Support for multiple files in Page feed

### ISSUE THREAD

**Issue by brunomcuesta** [mobolic/facebook-sdk#435]
Hello!
How to upload multiple files to a Page feed? In the [Doc](https://github.com/mobolic/facebook-sdk/blob/master/docs/api.rst) only an image upload appears and using the _put_photo_ method.

`graph.put_photo(image=open('img.jpg', 'rb'), message='Look at this cool photo!')`

I expected an option like this:

`graph.put_object(parent_object=facebook_uid, connection_name="feed", message="Sending mutiple files!", images=[image.jpg, image2.jpg])`

It would be possible?

**Comment by martey** [comment]
This issue tracker is for bug reports and feature requests. For general questions about how to use the library, please post to the [Google Group](https://groups.google.com/group/pythonforfacebook). If you decide to post there, you might want to follow the advice in http://zellwk.com/blog/asking-questions/ to increase the chances that your question is answered.
