### ISSUE TITLE
Get "Insights" data of a facebook page

### ISSUE THREAD

**Issue by ankitarath2011** [mobolic/facebook-sdk#449]
PLEASE DELETE THE ABOVE AFTER READING IT AND FILL IN EACH OF THE FOLLOWING SECTIONS.

### Expected Behavior - Tried fetching the Insights data of a page. But not getting anything. Used following code.
```
import facebook

graph = facebook.GraphAPI(access_token="your_token", version="3.1")
insights= graph.get_connections("me", "insights")
```

**Comment by martey** [comment]
See https://github.com/mobolic/facebook-sdk/issues/448#issuecomment-466494864.
