### ISSUE TITLE
Project release schedule

### ISSUE THREAD

**Issue by bsolomon1124** [mobolic/facebook-sdk#454]
Hi and thanks for all your work on this repo.

Does this project have an official PyPI release schedule?

The Facebook Graph API version 3.2 has been public for several months now; however, version 3.2.0 of `facebook-sdk` has been unreleased since January 2019 despite it being `master`.  (I understand if that is due to material changes in the structure of the API responses.  But it would be nice to have at least an informal timeline of when 3.2.0 will be the latest PyPI version.)

**Comment by martey** [comment]
General questions like this should be posted to https://groups.google.com/group/pythonforfacebook. In this case, [your question has already been answered there](https://groups.google.com/forum/#!msg/pythonforfacebook/a-7cLVLXncg/DSi8NmLRBAAJ).
