### ISSUE TITLE
Page feed 

### ISSUE THREAD

**Issue by martinbouhier** [mobolic/facebook-sdk#468]
I can't extract all posts from mercadopago page. Do you know what is going on?
For example, from 2020 year the facebook page have 3 posts and the script returns only 2.

import facebook
import requests
token = 'TOKEN'
graph = facebook.GraphAPI(token)
posts = graph.get_connections('mercadopago', "posts")
posts = posts['data']

**Comment by martey** [comment]
This issue tracker is for bug reports and feature requests. For general questions about how to use the library, please post to the [Google Group](https://groups.google.com/group/pythonforfacebook). If you decide to post there, you might want to follow the advice in http://zellwk.com/blog/asking-questions/ to increase the chances that your question is answered.
