### ISSUE TITLE
the package version is too old

### ISSUE THREAD

**Issue by wuyazi** [mobolic/facebook-sdk#476]
the last tag is v3.1.0, that is different with the master branch,
v3.1.0 tag:
VALID_API_VERSIONS = ["2.8", "2.9", "2.10", "2.11", "2.12", "3.0", "3.1"]
the master branch:
VALID_API_VERSIONS = ["3.0", "3.1", "3.2", "3.3", "4.0", "5.0", "6.0", "7.0"]

so, can you create a new tag with the new code?

when i run 'pip install facebook-sdk', i can install the newest package.

**Comment by martey** [comment]
See https://facebook-sdk.readthedocs.io/en/latest/install.html#installing-from-git and https://groups.google.com/forum/#!msg/pythonforfacebook/a-7cLVLXncg/DSi8NmLRBAAJ.
