### ISSUE TITLE
How to get photo and message of a specific post via URL

### ISSUE THREAD

**Issue by ntung** [mobolic/facebook-sdk#479]
Hello,

I am using this library to download the photo and message of a given URL. I dug out the documentation but haven't known how to achieve the purpose.

Thank you for your help!

**Comment by martey** [comment]
This issue tracker is for bug reports and feature requests. For general questions about how to use the library, please post to the [Google Group](https://groups.google.com/group/pythonforfacebook). If you decide to post there, you might want to follow the advice in http://zellwk.com/blog/asking-questions/ to increase the chances that your question is answered.
