### ISSUE TITLE
get all connections support time-based pagination

### ISSUE THREAD

**Issue by aliasadi92** [mobolic/facebook-sdk#481]
get all connections a node using since and until parameters

**Comment by martey** [comment]
This issue tracker is for bug reports and feature requests. If this is a bug report or feature request, please comment with more information.

If you have a general question about how to use the library, please post to the [Google Group](https://groups.google.com/group/pythonforfacebook). If you decide to post there, you might want to follow the advice in http://zellwk.com/blog/asking-questions/ to increase the chances that your question is answered.
