### ISSUE TITLE
Release support for Graph API version 8.0

### ISSUE THREAD

**Issue by aung-ko** [mobolic/facebook-sdk#482]
### Version of the SDK being used
v3.1.0

### Expected Behavior
support for Graph API v8.0

### Actual Behavior
does not support for Graph API v8.0 

### Steps to Reproduce
Please release the latest version which supports for Graph API version v8.0

**Comment by martey** [comment]
If you need support for Graph API v8.0, please use the instructions in the documentation to install from Git.

**Comment by aung-ko** [comment]
Yes, but we need PyPI attribution since we are working with pipenv for both development and production.

**Comment by aung-ko** [comment]
> If you need support for Graph API v8.0, please use the instructions in the documentation to install from Git.

Yes, but we need PyPI attribution since we are working with pipenv for both development and production.
