### ISSUE TITLE
Why it's no v.8, but still 3.1.0 that is deprecated?

### ISSUE THREAD

**Issue by 1st** [mobolic/facebook-sdk#483]
It's deprecation of the GraphQL API v.3.1.0 this October. Why do you not release a new versions of this app to the PyPI? We need to make upgrade to the v.8 today or tomorrow to omit deprecation. Thx

**Comment by CarlosMenaPhotoslurp** [comment]
same here! Im using the version 3.1.0, I need the same version but supporting the v3.3:
VALID_API_VERSIONS = ["2.8", "2.9", "2.10", "2.11", "2.12", "3.0", "3.1", "3.3"]

**Comment by martey** [comment]
This issue tracker is for bug reports and feature requests. For general questions about how to use the library, please post to the [Google Group](https://groups.google.com/group/pythonforfacebook). If you decide to post there, you might want to follow the advice in http://zellwk.com/blog/asking-questions/ to increase the chances that your question is answered.

**Comment by 1st** [comment]
@martey but you can find the same question asked few months ago and do not have any answer yet. Looks that this library isn't actively supported. Maybe we need to switch to something else in such case.
