### ISSUE TITLE
login-facebook

### ISSUE THREAD

**Issue by administrasi17** [mobolic/facebook-sdk#485]
If you have a general question about how to use this SDK or Facebook's Graph API, you should be posting a question at https://groups.google.com/group/pythonforfacebook instead of creating an issue here. Bugs in the Graph API should be reported at https://developers.facebook.com/bugs/.

PLEASE DELETE THE ABOVE AFTER READING IT AND FILL IN EACH OF THE FOLLOWING SECTIONS.

**Comment by Joe18** [comment]
Could I please receive all notifications and messages for this email
account please

jfisher
