### ISSUE TITLE
get_connections fails to get friends

### ISSUE THREAD

**Issue by kaarthikeyapreyan** [mobolic/facebook-sdk#49]
Python 2.7.3
facebook_sdk-0.3.2-py2.7.egg

> > > graph.get_connections(profile["id"], "friends")

Traceback (most recent call last):
  File "sdkref.py", line 31, in <module>
    friends = graph.get_connections(profile["id"], "friends")
  File "C:\Program Files (x86)\Python27\lib\site-packages\facebook.py", line 111, in get_connections
    return self.request(id + "/" + connection_name, args)
  File "C:\Program Files (x86)\Python27\lib\site-packages\facebook.py", line 275, in request
    raise GraphAPIError(response)
facebook.GraphAPIError: Unsupported operation

**Comment by rajasimon** [comment]
sorry I'm having this problem now... 


`friends = graph.get_connections(id='me', connection_name='', fields="friends")
`

and the print of friends is

`{'friends': {'data': [], 'summary': {'total_count': 427}}, 'id': '10154052898937398'}`

**Comment by martey** [comment]
@rajasimon, there are a number of reasons why the list of friends might be empty that do not relate to bugs in this application. I would advise posting to the Google Group for more support: https://groups.google.com/forum/#!forum/pythonforfacebook
