### ISSUE TITLE
Update supported versions

### ISSUE THREAD

**Issue by mssalnikov** [mobolic/facebook-sdk#498]
Facebook just sent out a letter that they stop supporting APIs lower than 8.2. The current version is 12.0. I only use /me request to get user data, and can't use this library at all now

### Version of the SDK being used
9.0

### Expected Behavior
I can call a request to /me

### Actual Behavior
The highest supported version is 8.0

### Steps to Reproduce
Use any of the API versions above 8.0

**Comment by hingston** [comment]
What needs to be done to update this to version 9.0?

@mobolic @martey Do you plan on continuing support?

**Comment by mssalnikov** [comment]
I only use login in my app, so I just forked and changed the list of supported versions 
https://github.com/mssalnikov/facebook-sdk
May be helpful

**Comment by hingston** [comment]
That is helpful but going forward I will need a more permanent solution after 9.0. Do you or anyone else reading this know of other python solutions to this beyond 8.0?

**Comment by martey** [comment]
The Graph API version should be transparently upgraded (https://developers.facebook.com/docs/graph-api/guides/versioning#howlong):

> For APIs, once a version is no longer usable, any calls made to it will be defaulted to the next oldest, usable version.
