### ISSUE TITLE
document how to use pagination

### ISSUE THREAD

**Issue by martey** [mobolic/facebook-sdk#85]
Multiple comments on #47 ask that we document how to properly use pagination with the Graph API.

**Comment by martey** [comment]
This is important, but in the interests of getting a new version out as soon as possible, I don't think it needs to be part of 1.0.0.

If someone wants to update the documentation (you could use 6169cae69949eb8948268b15c2dc21862b5cb7d8 as a template), pull requests will definitely be accepted.

**Comment by vanatteveldt** [comment]
First off, thanks for writing this client binding!

The example for paging switches from using graph.get_connections to doing a request directly. This is fine, of course, but it sidesteps the graph.request code, especially checks such as https://github.com/mobolic/facebook-sdk/blob/master/facebook/__init__.py#L271. 

I now do something like this:
https://gist.github.com/vanatteveldt/4ae7c7464c923008f8ff514228409577

Which I think would make a nice extra method next to the original `get_connections`, either yielding items or yielding the whole post json. If you agree, I can make a pull request?

**Comment by ihhcarus** [comment]
Any info on when we are getting a release of this?

**Comment by martey** [comment]
This issue was fixed by #337.

@ihhcarus, you can estimate the time of the next release by checking [the changelog](https://github.com/mobolic/facebook-sdk/blob/master/docs/changes.rst) to figure out what the next planned release is going to be (e.g. v3.0.0) and then checking [the appropriate milestone](https://github.com/mobolic/facebook-sdk/milestones) to figure out how many open issues remain that I would like to get fixed in that release.

FYI, general questions are better suited to [the Google Group](https://groups.google.com/forum/#!forum/pythonforfacebook) than to Github.

**Comment by datalin** [comment]
How come its a fix for graph.search()
